# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8s Terraform Azure!
  displayName: 'Are we here'


- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_kube.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure_kubernetes'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'stgaccgiri2021'
    backendAzureRmContainerName: 'stgacctgiri2021container'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
 
- task: TerraformCLI@0
  inputs:
    command: 'forceunlock'
    allowTelemetryCollection: true



- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure_kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_keys=$(publickey.secureFilePath)'
    allowTelemetryCollection: true
  