trigger:
- main

resources:
- repo: self

variables:
  #tag: '$(Build.BuildId)'
  tag: 32
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'dockerconn'
    #     repository: 'girilv/currency-exchange-devops'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'

    
    - task: CopyFiles@2
      inputs:
       SourceFolder: '$(System.DefaultWorkingDirectory)'
       Contents: '**/*.yaml'
       TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'


- stage: Deploy
  displayName: Deploy image
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        vmImage: ubuntu-latest
      steps:

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          itemPattern: '**/*.yaml'
          targetPath: '$(System.ArtifactsDirectory)'


      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'azure-kubernetes-connection'
          namespace: 'default'
          manifests: '$(Build.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
          containers: 'girilv/currency-exchange-devops:$(tag)'
          
#Stage 1
#Build Docker Image
#Publish the K8S files
#Stage 2
#Get K8s configuration
#Deploy to KBS Cluster